---
version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:80

  backend:
    build:
      context: ./backend
    ports:
      - 8000:8000
    environment:
      - MM_DB_PATH=/var/db/moviemanager
    volumes:
      - ${MM_DB_PATH:-./backend/db}:/var/db/moviemanager
